<?php

/**
 * JobeetJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return JobeetJobTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetJob');
    }

    public function getActiveJobs(Doctrine_Query $q = null)
    {
        return $this->addActiveJobsQuery($q)->execute();
    }

    public function countActiveJobs(Doctrine_Query $q = null)
    {
        return $this->addActiveJobsQuery($q)->count();
    }

    public function addActiveJobsQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('JobeetJob j');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.expires_at > ?', date('Y-m-d h:i:s', time()))
            ->addOrderBy($alias . '.expires_at DESC');

        $q->andWhere($alias . '.is_activated = ?', 1);

        return $q;
    }

    public function retrieveActiveJob(Doctrine_Query $q)
    {
//        $q->andWhere('a.expires_at > ?', date('Y-m-d h:i:s', time()));
//        return $q->fetchOne();

        return $this->addActiveJobsQuery($q)->fetchOne();
    }

    static public $types = array(
        'Tiempo Completo' => 'Tiempo Completo',
        'Medio Tiempo' => 'Medio Tiempo',
        'Por Contrato' => 'Por Contrato',
    );

    public function getTypes()
    {
        return self::$types;
    }

    public function cleanup($days)
    {
        $q = $this->createQuery('a')
            ->delete()
            ->andWhere('a.is_activated = ?', 0)
            ->andWhere('a.created_at < ?', date('Y-m-d', time() - 86400 * $days));

        return $q->execute();
    }

}