generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JobeetJob
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          jobeet_job
    with_doctrine_route:   true

    config:
      actions: ~
      fields:
        is_activated: { label: Activado?, help: Trabajo listo para mostrar al mundo }
        is_public:    { label: Publico?, help: Cualquier usaurio puede ver el trabajo o solo afiliados a la pagina }
      list:
        sort: [expires_at, desc]
        title: Administrar Trabajo
        layout:  stacked
        display: [company, =position, location, url, is_activated, email]
        params:  |
          %%is_activated%% <small>%%JobeetCategory%%</small> - %%company%%
           (<em>%%email%%</em>) Necesita un %%=position%% en (%%location%%)
        max_per_page: 10
        batch_actions:
          _delete:    ~
          extend:     ~
        object_actions:
          extend:     ~
          _edit:      ~
          _delete:    ~
        actions:
          deleteNeverActivated: { label: Borrar trabajos no activados }
        table_method: retrieveBackendJobList
      filter:
        display: [category_id, company, position, description, is_activated, is_public, email, expires_at]
      form:
        display:
          Content: [category_id, type, company, logo, url, position, location, description, how_to_apply, is_public, email]
          Admin:   [_generated_token, is_activated, expires_at]
        class: BackendJobeetJobForm
      edit:
        title: Editando Trabajo -> "%%company%% en busqueda de un %%position%%"
      new:
        title: Nuevo Trabajo
