<?php

/**
 * JobeetJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetJobTable extends PluginJobeetJobTable
{
    /**
     * Returns an instance of this class.
     *
     * @return JobeetJobTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetJob');
    }
}